# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_inside <- function(points) {
    .Call('_ptds2018hw4g5_is_inside', PACKAGE = 'ptds2018hw4g5', points)
}

df_pi <- function(B) {
    .Call('_ptds2018hw4g5_df_pi', PACKAGE = 'ptds2018hw4g5', B)
}

